Feature: Dynamic Page Scrape

  Scenario: Scrape data from dynamically loaded listing page
    Given a dynamic page is loaded
    When the page is parsed
    Then there are 16 result pages returned with a total value of 35.50
    And the following data is parsed from the pages
      | index | title                                                   | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | unit price |
      | 0     | Sainsbury's Apricot Ripe & Ready x5                     | Apricots                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 3.50       |
      | 1     | Sainsbury's Avocado Ripe & Ready XL Loose 300g          | Avocados                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 1.50       |
      | 2     | Sainsbury's Avocado, Ripe & Ready x2                    | Avocados                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 1.80       |
      | 3     | Sainsbury's Avocados, Ripe & Ready x4                   | Avocados                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 3.20       |
      | 4     | Sainsbury's Conference Pears, Ripe & Ready x4 (minimum) | Conference                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1.50       |
      | 5     | Sainsbury's Golden Kiwi x4                              | Gold Kiwi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 1.50       |
      | 6     | Sainsbury's Kiwi Fruit, Ripe & Ready x4                 | Kiwi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 1.50       |
      | 7     | Sainsbury's Kiwi Fruit, SO Organic x4                   | Kiwi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 1.00       |
      | 8     | Sainsbury's Mango, Ripe & Ready x2                      | by Sainsbury's Ripe and Ready Mango                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | 2.00       |
      | 9     | Sainsbury's Nectarines, Ripe & Ready x4                 | Description Ripe & ready Great to eat now - refrigerate at home 1 nectarine counts as 1 of your 5 a-day Source of vitamin C Class 1 Film - Plastic - not currently recycled Tray - Paper - widely recycled                                                                                                                                                                                                                                                                                                                         | 3.00       |
      | 10    | Sainsbury's Papaya, Ripe (each)                         | Papaya                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | 1.50       |
      | 11    | Sainsbury's Peaches Ripe & Ready x4                     | Peach                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 3.50       |
      | 12    | Sainsbury's Pears, Ripe & Ready x4 (minimum)            | Pear                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 1.50       |
      | 13    | Sainsbury's Plums Ripe & Ready x5                       | Plums                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 3.50       |
      | 14    | Sainsbury's Ripe & Ready Red Pears x4                   | Description Sweet & Juicy Blush Pears Ripe & ready Sweet & Juicy One pear counts as 1 of your 5 a-day One pear counts as 1 of your 5 a-day Aim for at least 5 different portions of fruit or veg a day. Fresh, frozen, dried, canned and juice all count. We value the quality of fresh fruit and vegetables We are proud to work in partnership with our suppliers, who participate in an independent audit programme that ensures responsible pesticide usage and encourages environmental protection and wildlife conservation. | 1.50       |
      | 15    | Sainsbury's White Flesh Nectarines, Ripe & Ready x4     | by Sainsbury's Ripe and Ready White Flesh Nectarines                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 3.50       |